### ISSUE TITLE
need help for CSPs

### ISSUE THREAD

**Issue by croghostrider** [rozek/node-red-within-express#1]
Hi Andreas,
first, your repository is amazing.

I try to allow bootstrap from cdn.jsdelivr.net, unfortunately without success.
Could you please help me to allow these two files: [file1](https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js), [file2](https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css).

Thanks.
Best regards 
Vinko

**Comment by croghostrider** [comment]
Sorry got it done myself.

**Comment by rozek** [comment]
Don't worry - thanks for the praise anyway!
