### ISSUE TITLE
Help to Start the Server after "npm install" steps

### ISSUE THREAD

**Issue by ChuaYS1025** [rozek/node-red-within-express#2]
Hi Andreas,

I love your this repositories "Node-Red within express" project and would like to explore it to develop a back-end system for one of my project.

However, I am a bit confuse on how to run the server after the "npm install" step.

Moreover, I am faced this issue while doing "npm install" showing 7 vulnerabilities at below:
![image](https://user-images.githubusercontent.com/106689692/175765259-8ae2589a-eccb-4d8d-b6ef-50ecd4ed73a4.png)

Should I ignore it and straight run/start the server? Kindly advise me on it

Can you kindly also advise the following steps to run/start the server? As I dont really understand the next steps on how it should be done.

Thanks in advance for the support. 

Looking forward to your reply soon.

FYI, I am using Window to run this repositories.

**Comment by rozek** [comment]
Hello,

as the log states, vulnerabilites will be fixed by installing `node-red@1.3.7`, but this is described as a "breaking change".

Right now I do not have the time to test it myself - but what *you* may want to try is installing the mentioned version of NodeRED rather than the requested one and see whether the server (and the foreseen NodeRED flows) will still work as intended.

The mentioned vulnerabilities sound severe - for that reason, if you plan to use NodeRED as a backend, you may really want to give the new versoin a try!

How to run the final server will depend on whether you need "virtual hosts" or not - "virtual hosts" will be required if multiple domain names (e.g., a.de, b.de, c.de etc.) will be resolved to the same IP address and handled by the same actual server (which, internally, may direct any requests to domain-specific subdirectories in order to isolate domains from each other)

**Comment by ChuaYS1025** [comment]
Hi,

I will

**Comment by ChuaYS1025** [comment]
Hi,

I will try to explore around to test whether it works with both node-red@1.3.7 or the new version node-red.

Thanks for the sharing.

**Comment by rozek** [comment]
Please inform me about your result - it might be a good idea to change the `package.log` accordingly

**Comment by ChuaYS1025** [comment]
Hi Andreas,

I have do some research on 7 vulnerabilities package. Based on node red forum, it doesn't affect the application and can continue to use it. Node-red developers will also resolve these vulnerabilities packages at next node-red 2.2.3 update.

However, my question is how do I start the server using "without virtual hosts processing". As I type in npm run in the VS code terminal, it will pop out error at below:
![image](https://user-images.githubusercontent.com/106689692/177366682-34fd09f2-95a3-42e1-9a39-2f94eefb5e05.png)

Your instruction manual is not very clear to both me and my teammates who are doing testing on your repository and trying to start the server and access the embedded Node-red to start our first node-red flow.
![image](https://user-images.githubusercontent.com/106689692/177367443-c0f9b7a8-0ed6-49df-b851-d753d2a46ed7.png)

Is it possible for you to kindly to share some tips on starting the server "without virtual hosts processing" and accessing to node-red to start our first node-red flow?

We really need help and input from you so that we can really start using your repository.

Looking forward to your reply.

**Comment by rozek** [comment]
Hello,

from your terminal output, I assume that you are using some kind of Windows system (e.g., 10 or 11).

In that case, you may succeed by renaming `startServerWithoutDomains` to `startServerWithoutDomains.bat` (and removing the shebang line).

Alternatively, you may just run the single command in that script file directly from your terminal input line:

```
node WebServer.js public/local-server.org
```

(just change the directory name to match your domain, `node` must be in your command path, and the current working directory must be the repository base folder)

Kind regards,

Andreas Rozek

**Comment by ChuaYS1025** [comment]
Hi Andreas,

Thanks a lot for this tips. I have successfully started the server and access into the node-red flow.

Will start designing my project system architecture using your repositories.
![image](https://user-images.githubusercontent.com/106689692/178215052-3aeda56f-f968-49f5-bfda-720949692c88.png)

Really appreciated your help on this issue. 

Kindly regards,
YS Chua

**Comment by rozek** [comment]
You are welcome!

I'll try to update my documentation with regard to Windows in the next few days
